### ISSUE TITLE
Add a weekly digest newsletter

### ISSUE THREAD

**Issue by garaud** [ertugrulcetin/ClojureNews#11]
Hi,

Is is possible to send an email to all users with recent stories and new comments, every week (or day according to the activity)?
I'm a Clojure beginner but I would like to help if I can.

Cheers,
Damien

**Comment by ertugrulcetin** [comment]
@garaud Yes you can write a job and create a pull request :)

**Comment by garaud** [comment]
Finally, I did the job with a few lines of Python. I requested the latest entries from the mongo db, filled a HTML template with jinja2 and sent an email to my team. I've a cron job which runs the script every week.

For your information, I deployed this great project at work to write and share some news. It was a quite complicated and not very straightforward for me to (1) modify the account form _subscribe to the newsletter?_, (2) modify the data model in the DB to store this information, (3) write the sending email part with a well SMTP configuration and (4) find a way to schedule the newsletter sending.

You can take a look to this Gist if you like
https://gist.github.com/garaud/e141b530f80e28e58d05e0651444cffb

Maybe I can close the issue. What do you think?
Cheers,
Damien

**Comment by ertugrulcetin** [comment]
@garaud Wow that's very nice! Thank you for this development. I'll do major update couple of months later and going to strongly consider to implement this feature that you wrote for ClojureNews!

**Comment by garaud** [comment]
For the sending part, I don't upload the Python script, but this is very straightforward when you generate the HTML file. Note that I've some Bootstrap CSS locally installed from bower in the HTML header of my file. In order to have a shiny email, you have to inline all the CSS. This is why, before sending the generated HTML file, I use [gulp-inline-css](https://www.npmjs.com/package/gulp-inline-css). This creates a new HTML file with inlined CSS which is ready to send.

**Comment by ertugrulcetin** [comment]
@garaud Thank you for letting me know and you can close the issue if you want to.
