### ISSUE TITLE
Clojure related stories don't appear in ClojureNews

### ISSUE THREAD

**Issue by viebel** [ertugrulcetin/ClojureNews#7]
The following clojure related stories don't appear in ClojureNews:
1. https://news.ycombinator.com/item?id=12185523
2. https://news.ycombinator.com/item?id=12202039

**Comment by ertugrulcetin** [comment]
@viebel Because users need to submit those stories into Clojure News(from scratch). Clojure News is not related with Hacker News (API Layer)

You can submit stories by using this link: https://clojure.news/#/submit

**Comment by viebel** [comment]
Sorry for the misunderstanding.

**Comment by ertugrulcetin** [comment]
No problem :)
