### ISSUE TITLE
Open links in same window option?

### ISSUE THREAD

**Issue by wardes** [ertugrulcetin/ClojureNews#9]
Hi,
 Thanks for the ClojureNews site.  I have a suggestion: to allow toggling of links being opened in a new tab or not.  Perhaps it could be a setting for logged in users, or even just a checkbox on the main screen (saved as a cookie?). I think the usability on mobile especially would be better to just use the back button.

cheers,
Simon

**Comment by ayazmaroof** [comment]
Actually, I was wondering about that too. Hacker news links always open in the same tab. If I want to open a story in a new tab on Hacker news, I usually do it manually. 
I am just curious about what the initial motivation was for the links opening in new tabs?

**Comment by ertugrulcetin** [comment]
@wardes @ayazmaroof Actually, I did not think too much on that feature.
I can change to "open in the same tab".
What do you think?

**Comment by ayazmaroof** [comment]
@ertugrulcetin Sounds good to me. 
Btw, thanks for the website. I am loving it!

**Comment by wardes** [comment]
Hi, just opening in the same tab gets my vote, I didn't know if there was any preference for the new tab choice in the first place.

**Comment by ertugrulcetin** [comment]
@wardes @ayazmaroof I just changed functionality to "open in the same tab".
